### ISSUE TITLE
/swapi-graphql is broken again

### ISSUE THREAD

**Issue by benjie** [graphql/graphql.github.io#1618]
https://graphql.org/swapi-graphql/ - 404

### Description

Previously:

- #1427 

### Steps to Reproduce

https://graphql.org/swapi-graphql/

### Expected Result

SWAPI GraphQL

### Actual Result

404

### Additional Context

Possibly caused by https://github.com/graphql/graphql.github.io/pull/1602/files cc @YassinEldeeb @Urigo

**Comment by acao** [comment]
do we have any updates on this? I've had users complaining about this almost weekly

**Comment by YassinEldeeb** [comment]
With our current setup, our Gatsby app which is deployed on Vercel now. We can't have rewrite pages anymore as we did with Gatsby Cloud. We can only redirect people off the site to the swapi domain. I did try to fix it, but the only way to do it is to redirect people off to another domain which is not great.

There's an ongoing refactoring to Next.js which will easily allow us to enable the "rewrite" feature for pages like swapi. So, after that is merged, this should be fixed. #1604

**Comment by acao** [comment]
thank you for the update @YassinEldeeb and thanks for working on this!

yes i agree, a redirect off domain is not ideal, good choice. can we add reverse proxy to another domain to vercel currently to patch this until the next.js rewrite lands? would it help if i move swapi graphql from netlify to vercel?

**Comment by YassinEldeeb** [comment]
@acao I’d maybe advocate for the second option, as this would ultimately be the best implementation for now and later. Is it possible to directly deploy this on our Gatsby app on Vercel? 👀 


I’m not fully aware about how this endpoint is maintained, but maybe you have more context on the feasability of directly deploying it within our app instead of doing a “rewrite”
https://github.com/graphql/graphql.github.io/blob/253cf75bf5710f08df0d73f7cd6863331bb10ed1/vercel.json#L20

**Comment by acao** [comment]
we just publish it to netlify. I'm not sure why the old github.io URL is still being used, might have been my mistake after we migrated to netlify so we could have an actual backend schema instead of a client-side-only schema on gh pages. we should be using `https://swapi-graphql.netlify.app/`

netlify config:
https://github.com/graphql/swapi-graphql/blob/master/netlify.toml

you can see it in the graphql netlify org

**Comment by acao** [comment]
thanks @Urigo !!!
