### ISSUE TITLE
Add graphql-tools reference to GraphQL.js tutorial

### ISSUE THREAD

**Issue by stubailo** [graphql/graphql.github.io#318]
Right now a lot of people are running into confusion with the `buildSchema` approach in the [getting started guide](http://graphql.org/graphql-js/), there are a few things that are confusing about it:

1. The root object isn't the same as the usual resolvers. Resolvers have a signature of `(root, args, context)`, but with the `rootValue` object instead you get `(args, context)`.
2. You get stuck as soon as you need interfaces or unions. [SO question that reminded me here.](https://stackoverflow.com/questions/44246290/how-to-use-unions-with-graphql-buildschema/)
3. There isn't a clear way to scale up to multiple files.

For a bit over a year we've had the `graphql-tools` package which addresses exactly these concerns but doesn't introduce any additional opinions: http://dev.apollodata.com/tools/graphql-tools/generate-schema.html

It would be pretty much a drop-in replacement for `buildSchema` in the tutorial, would be happy to make the switch if people think this could be a good idea.

Here's an example of how the code would change:

### With buildSchema, currently

```js
var { graphql, buildSchema } = require('graphql');

// Construct a schema, using GraphQL schema language
var schema = buildSchema(`
  type Query {
    hello: String
  }
`);

// The root provides a resolver function for each API endpoint
var root = {
  hello: () => {
    return 'Hello world!';
  },
};

// Run the GraphQL query '{ hello }' and print out the response
graphql(schema, '{ hello }', root).then((response) => {
  console.log(response);
});
```

### With graphql-tools

```js
var { graphql } = require('graphql');
var { makeExecutableSchema } = require('graphql-tools');

// Construct a schema, using GraphQL schema language
var typeDefs = `
  type Query {
    hello: String
  }
`;

// The provide a resolver function for each query field
var resolvers = {
  hello: () => {
    return 'Hello world!';
  },
};

var schema = makeExecutableSchema({
  typeDefs: typeDefs,
  resolvers: resolvers
});

// Run the GraphQL query '{ hello }' and print out the response
graphql(schema, '{ hello }').then((response) => {
  console.log(response);
});
```

Also looking at that snippet there are some oddities like the text "resolver function for each API endpoint", which I'd be happy to fix while I'm there.

**Comment by OlegIlyenko** [comment]
I wonder whether it would be possible to add some of the features from `graphql-tools` in `buildSchema`? Things like `__resolveType` sound like a very good addition to support interface and union types.

AFAIR, as `buildSchema` it was introduced, it's main purpose was to build schema for validations and introspection, but not actual execution (please correct me if I got it wrong). The dynamics have changed since then and people started to use it more and more for the actual execution (even the docs recommend this). If it is the case, I think it would be a very good idea to improve `buildSchema` in `graphql-js` to reflect this new approach. WDYT?

**Comment by stubailo** [comment]
I think `buildSchema` as a single function was introduced specifically for this tutorial by @lacker, and using it in the getting started tutorial was a conscious choice to recommend using the schema language.

While I do think it would be great if `buildSchema` was improved to include some of these other features, I think it will be much easier for us to iterate quickly if that was kept outside of GraphQL.js, because these features are pretty orthogonal to a reference implementation.

**Comment by wincent** [comment]
I think @OlegIlyenko has a good point. The tutorial is called "Getting Started With GraphQL.js", so I think we should probably:

1. Keep it about GraphQL.js.
2. Look at rolling improvements into GraphQL.js to make it easier to use (either enhancing `buildSchema` or adding another API).
3. Add references to `graphql-tools` showing that it provides another, arguably simpler, way to build a schema.

(Or more realistically, swap the order of 2 and 3 because that'll deliver value sooner and cheaper.)

**Comment by stubailo** [comment]
OK - I think a reasonable start might be to add a callout to `graphql-tools` here: http://graphql.org/graphql-js/constructing-types/

Will send a PR with that!

**Comment by leebyron** [comment]
Closing this issue - take away sounds on point. Always good to reference other tools, but keeping examples about the lib requiring as few additional dependencies as possible is the right outcome.
