### ISSUE TITLE
Resolver parameter order documented incorrectly

### ISSUE THREAD

**Issue by steve-taylor** [graphql/graphql.github.io#358]
According to the documentation, resolver functions are written as follows:

```js
function someField(obj, args, context) {
  // Return something...
}
```

However, when I build resolver functions, the parameters provided by GraphQL are

* `args`
* `context`
* `obj`

So I end up having to build resolvers as follows:

```js
function someField(args, context, obj) {
   // Return something...
}
```

My understanding of these parameters is as follows:

* `obj` - the parent object, if any
* `args` - contains the arguments passed to the field in the query (e.g. when executing the query `query { someField(foo: "bar") }`, `args` is set to `{foo: 'bar'}`
* `context` - the object provided as the 4th parameter to the `graphql` function

Am I missing something or are is the documentation incorrect?

**Comment by leebyron** [comment]
The documentation is probably just not clarifying the difference between resolver API and the default resolver behavior.

The resolver API is correct as written. Object is always the first parameter.

However if a resolver is not provided, the default is used, which looks for a method on the object of the same name as the field. If it finds one, it calls it with the args and context (since it is a method of the object, the obj can always be accessed as `this`).

I've just added some additional info in fc7c390a4919c1bacd8bafe510147dfd026860fe mentioning this.
