### ISSUE TITLE
none of the example can be run on standard graphiql

### ISSUE THREAD

**Issue by patriklindstrom** [graphql/graphql.github.io#401]
I tryed to past them in http://graphql.org/swapi-graphql and non of them worked. Why ? Is that not the obvious thing to do? examples from starwars. Here is a star wars standard simple hello world api. No none of the examples can be used to experiment with.  "message": "Cannot query field \"hero\" on type \"Root\". Did you mean \"person\"?". This is supposed to be a fun intro to GraphQl not a sudoku puzzle

**Comment by hwillson** [comment]
Sorry for the delay in responding here @patriklindstrom.

There are many different versions of the Star Wars API floating around, including many different versions within the GraphQL space. As great as it would be to have the https://graphql.org learn docs use the same version as https://github.com/graphql/swapi-graphql, it would be very difficult to keep them in sync. The learn docs are intended to help GraphQL newcomers with their introductory journey, and an earlier version of the Start Wars API was picked as being a good fit schema wise for that initial journey. The `swapi-graphql` project however is intended to be an up to date GraphQL based port of https://github.com/Juriy/swapi. The learn docs don't need to be kept up to date with an external API; they just need enough context to help users learn about GraphQL, which is why they haven't kept pace. Given this (and the age of this issue) we'll close this off for now. Thanks!
