### ISSUE TITLE
Human Type under interfaces

### ISSUE THREAD

**Issue by guptad2** [graphql/graphql.github.io#563]
Steps to reproduce:
Visit: http://graphql.github.io/learn/schema/ 

Under Interfaces where we have 
```
... on Droid {
      primaryFunction
    }
```
 add 
```
... on Human {
      totalCredits
     }
```

After that, change totalCredits to height and the error goes away. 

<img width="1920" alt="screen shot 2018-08-15 at 1 54 05 pm 2" src="https://user-images.githubusercontent.com/24924707/44172921-5f0b1a80-a093-11e8-81d7-7d2a9af9da8c.png">

<img width="1920" alt="screen shot 2018-08-15 at 1 54 17 pm 2" src="https://user-images.githubusercontent.com/24924707/44172939-69c5af80-a093-11e8-83be-957adcaa31ce.png">

This is probably happening because this query is using the type 'Human' from one of the previous pages that have the field height

**Comment by carolstran** [comment]
👋🏼 @guptad2, thanks for opening an issue on the GraphQL docs! Since this issue was opened a while ago (😬😅), it seems it has resolved itself. The code sample you mentioned now only has the `on Droid` and no `on Human`. Now the only remaining error is intentional.

I'll close this for now - but if I misunderstood, please let me know!
