### ISSUE TITLE
404 error for docsearch in browser console.

### ISSUE THREAD

**Issue by theNaut1lus** [graphql/graphql.github.io#690]
url: https://graphql.org
On opening the website on my browser (Safari 12.1), I found that the website gave out a console error for the following resource.
`https://cdn.jsdelivr.net/docsearch.js/1/dist/cdn/docsearch.min.js.map`
<img width="1278" alt="Screenshot 2019-04-18 at 11 06 37 PM" src="https://user-images.githubusercontent.com/35738138/56380013-ab17eb80-622e-11e9-851d-b5785da162ae.png">

**Comment by aranhaagency** [comment]
This docsearch update version 2.6.3 not version 1. Check this (https://www.jsdelivr.com/package/npm/docsearch.js)[docsearch.js 2.6.3]

**Comment by carolstran** [comment]
@co16353sidak, thanks for opening an issue on the GraphQL docs! I know it's been a while, but I'm also seeing the 404 error (on Firefox it's a warning instead of an error, but same issue). 

Would you be open to help fix the issue? No pressure, I can also put a `Help wanted` label on it. As far as I can tell, it doesn't affect the functionality so it wouldn't be a high priority bug to fix - but it's always nice to avoid console errors.

**Comment by JanetLaysEggs** [comment]
@carolstran Can I please have this issue assigned to me?

**Comment by carolstran** [comment]
👋🏼  @JanetLaysEggs! Sorry I'm just seeing this notification. Do you still want to be assigned/work on this?

**Comment by Urigo** [comment]
I believe this is fixed on the new website, please reopen if that's not the case
