### ISSUE TITLE
Missing mutation result type in the doc "Mutations and Input Types"

### ISSUE THREAD

**Issue by MrOrz** [graphql/graphql.github.io#83]
Referred doc: http://graphql.org/graphql-js/mutations-and-input-types/
Source: https://github.com/graphql/graphql.github.io/blob/c22ba1a/site/graphql-js/Tutorial-Mutations.md

The result type of `createMessage` and `updateMessage` is missing in the schema and the "runnable code" example.
I was expecting the doc to specify the result of mutation types -- a simple boolean that indicates success/fail of the mutation? or just return the newly updated message instance?

Although it may not be the main concern of the article "Mutations and Input Types", but some insights on the design of return type of mutations would be great.

**Comment by lacker** [comment]
Ah true all the return type stuff in there seems borked. I was trying to simplify the example but I think I cut too much. I'll fix it. For a normal createMessage and updateMessage on a simple app I would suggest defaulting to returning the newly updated message instance - you're likely to want the newly-assigned id, and it's probably efficient to have that data accessible anyway. For a more complicated app it's nice to have something like a CreateMessagePayload type so that you can stick more random stuff in there. That's a Relay pattern at least. This doc might not go into all of that but it should be more accurate than it is now

**Comment by lacker** [comment]
OK I fixed this doc up in https://github.com/graphql/graphql.github.io/pull/85 - thanks for filing this issue.
