### ISSUE TITLE
Confused about reading Queries and Mutations - Using variables inside fragments section

### ISSUE THREAD

**Issue by Zhouchuanwen** [graphql/graphql.github.io#906]
Newbee Confused  about https://graphql.org/learn/queries/#fields

Why totalCount is 4, but edges only 3 returned.

![image](https://user-images.githubusercontent.com/7982753/90209880-0fe15700-de1f-11ea-88b1-40f66454f345.png)

I refer the other demo, Luke Skywalker's friendsConnection is really 4,  this page missed the node "R2-D2 " ?

**Comment by saswatamcode** [comment]
@Zhouchuanwen Over here we are setting a limit to the number of `friendsConnection` nodes that we want to get back from our query using the `$first` variable. Here we set first to 3 so we get back details of the first 3 nodes. But `totalCount` gives you the total number of nodes which is 4 here. If you change `first` to 4(you can since the examples are interactive) you should see 4 nodes. Hope this helps!

**Comment by Zhouchuanwen** [comment]
thx
